baseurl = "/"
title = "Stuff I Learned Today"
theme = "ghostwriter"
copyright = "2022 Jeremy Borgman All rights reserved"

[Params]
    author = { name = "Jeremy Borgman", email = "borgman.jeremy@pm.me" }
    mainSections = ["post"]
    intro = true
    headline = "Stuff I Learned"
    description = "I will use this blog to document things I've learned"
    github = "https://github.com/borgmanJeremy"
    rss = true
    opengraph = true
    disqusShortname = ""
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"